[project]
name = "rtdetrv2-pytorch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "faster-coco-eval>=1.6.5",
    "onnx>=1.18.0",
    "onnxruntime-gpu>=1.22.0",
    "opencv-python>=4.11.0.86",
    "pycocotools>=2.0.8",
    "pyyaml>=6.0.2",
    "scipy>=1.15.3",
    "tensorboard>=2.19.0",
    "tensorrt==8.5.2.2",
    "torch>=2.0.1",
    "torchvision>=0.15.2",
    "tqdm>=4.67.1",
]
